'use strict';

const OP_CODE_START_DFU_KEY = 0x01; // 1
const OP_CODE_INIT_DFU_PARAMS_KEY = 0x02; // 2
const OP_CODE_RECEIVE_FIRMWARE_IMAGE_KEY = 0x03; // 3
const OP_CODE_VALIDATE_KEY = 0x04; // 4
const OP_CODE_ACTIVATE_AND_RESET_KEY = 0x05; // 5
const OP_CODE_RESET_KEY = 0x06; // 6
const OP_CODE_PACKET_RECEIPT_NOTIF_REQ_KEY = 0x08; // 8
const OP_CODE_RESPONSE_CODE_KEY = 0x10; // 16
const OP_CODE_PACKET_RECEIPT_NOTIF_KEY = 0x11; // 17

const NUMBER_OF_PACKETS_BEFORE_NOTIF = 12;

angular
    .module('main')
    .constant('Constants', {
        GENERIC_ATTRIBUTE_SERVICE_UUID: '00001801-0000-1000-8000-00805f9b34fb',
        SERVICE_CHANGED_UUID: '00002a05-0000-1000-8000-00805f9b34fb',
        DFU_SERVICE_UUID: '00001530-1212-efde-1523-785feabcd123',
        DFU_CONTROL_POINT_UUID: '00001531-1212-efde-1523-785feabcd123',
        DFU_PACKET_UUID: '00001532-1212-efde-1523-785feabcd123',
        DFU_VERSION_UUID: '00001534-1212-efde-1523-785feabcd123',

        DFU_STATUS_SUCCESS: 1,
        DFU_STATUS_INVALID_STATE: 2,
        DFU_STATUS_NOT_SUPPORTED: 3,
        DFU_STATUS_DATA_SIZE_EXCEEDS_LIMIT: 4,
        DFU_STATUS_CRC_ERROR: 5,
        DFU_STATUS_OPERATION_FAILED: 6,

        OP_CODE_START_DFU_KEY: OP_CODE_START_DFU_KEY,
        OP_CODE_INIT_DFU_PARAMS_KEY: OP_CODE_INIT_DFU_PARAMS_KEY,
        OP_CODE_RECEIVE_FIRMWARE_IMAGE_KEY: OP_CODE_RECEIVE_FIRMWARE_IMAGE_KEY,
        OP_CODE_VALIDATE_KEY: OP_CODE_VALIDATE_KEY,
        OP_CODE_ACTIVATE_AND_RESET_KEY: OP_CODE_ACTIVATE_AND_RESET_KEY,
        OP_CODE_RESET_KEY: OP_CODE_RESET_KEY,
        OP_CODE_PACKET_RECEIPT_NOTIF_REQ_KEY: OP_CODE_PACKET_RECEIPT_NOTIF_REQ_KEY,
        OP_CODE_RESPONSE_CODE_KEY: OP_CODE_RESPONSE_CODE_KEY,
        OP_CODE_PACKET_RECEIPT_NOTIF_KEY: OP_CODE_PACKET_RECEIPT_NOTIF_KEY,

        OP_CODE_START_DFU: [ OP_CODE_START_DFU_KEY, 0x04 ], // always file
        OP_CODE_INIT_DFU_PARAMS_START: [ OP_CODE_INIT_DFU_PARAMS_KEY, 0x00 ],
        OP_CODE_INIT_DFU_PARAMS_COMPLETE: [ OP_CODE_INIT_DFU_PARAMS_KEY, 0x01 ],
        OP_CODE_RECEIVE_FIRMWARE_IMAGE: [ OP_CODE_RECEIVE_FIRMWARE_IMAGE_KEY ],
        OP_CODE_VALIDATE: [ OP_CODE_VALIDATE_KEY ],
        OP_CODE_ACTIVATE_AND_RESET: [ OP_CODE_ACTIVATE_AND_RESET_KEY ],
        OP_CODE_RESET: [ OP_CODE_RESET_KEY ],
        OP_CODE_PACKET_RECEIPT_NOTIF_REQ: [ OP_CODE_PACKET_RECEIPT_NOTIF_REQ_KEY, NUMBER_OF_PACKETS_BEFORE_NOTIF, 0x00 ],

        NUMBER_OF_PACKETS_BEFORE_NOTIF: NUMBER_OF_PACKETS_BEFORE_NOTIF
    } );
